/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125674-g9bc73ba3449"
#endif /* AVUTIL_FFVERSION_H */
